#!/bin/bash
echo "🧪 Testing Frontend Deposit Fix"
echo "================================"
echo ""
echo "1. Checking database values..."
php artisan tinker --execute="DB::table('ec_pre_order_products')->join('ec_products', 'ec_pre_order_products.product_id', '=', 'ec_products.id')->select('ec_pre_order_products.*', 'ec_products.name')->where('pre_order_id', 2)->get()->each(function(\$p) { echo \$p->name . ' => Deposit: ' . (\$p->deposit_amount ?? 'uses global') . PHP_EOL; });"
echo ""
echo "✅ Database check complete!"
echo ""
echo "2. Now test on FRONTEND:"
echo "   - Go to http://localhost"
echo "   - Add 'Vintage Denim Jacket' to cart"
echo "   - Go to checkout"
echo "   - Look for deposit amount: Should show 12,000 (NOT 15,000)"
echo ""
echo "3. Check logs:"
echo "   tail -f storage/logs/laravel.log"
